name: Linting

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Black Check
        run: uvx black --check .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: run isort
        run: uvx isort --check-only --quiet .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Install flake8
        run: uv pip install --system flake8 flake8-isort
      - name: run flake8
        run: flake8 . --count --show-source --statistics
